---
# Any global variables needed to be known ACROSS roles and hosts
# should be defined here.

required_domains:
        - openpgpkey
        - wkd
        - autoconfig
        - autodiscover
        - mta-sts
        - imap
        - pop3
        - smtp

extra_domains:
        - dav
        - webmail

subdomains: "{{ required_domains + extra_domains }}"

timezone: "US/Eastern"

username_delimiter: "+"

max_attachment_sizeM: 32
max_attachment_size: "{{ max_attachment_sizeM * 1048576 }}"

# these generally don't need to be changed even if you want
# to use a multi machine setup
relayd_interface: 127.0.0.1
relayd_port: 1729
https_interface: 127.0.0.1
https_port: 1984
http_interface: egress
http_port: 80

## webmail, caldav and carddav
#
# if you enable extras you have an option 
# to set them up on a separate machine and let the two machines
# interact with each other through a private network/VPN
# wireguard is a really good candidate to setup such a VPN
# in which case you can set the extrasIP to the wireguard peer IP 
# and in the above configuration set http/s interface to tun0/wg0
enable_extras: false
extrasIP: 127.0.0.1                        # if using wireguard, set to the peer ip of 
                                           # extraserver, like 10.7.0.3
extras_interface: "{{ https_interface }}"  # this should then be set to wg0/tun0
extras_port: "{{ relayd_port }}"           #
extras_not_home: false                     # this should then be set to true


#### other optionals
#
# if you don't enable nsd then all nsd: true domains will have
# no effect.
# HIGHLY RECOMMENDED to enable nsd and use it as it does a lot of 
# important management
enable_nsd: false
#
# if you are going to be using ipv6 for your domain
# you may want to disable spamd as it does not support ipv6 yet
# but its greylisting featureset is quite useful and it is recommended
# to enable it but if you don't enable you won't lose out on too much
enable_spamd: false
#
# clamav is an antivirus scanner and is really heavy on the
# machine. if you enable it be prepared to add another 1GB of RAM
# and another core to your setup.
# For most people enabling clamav is not really needed unless you
# are going to be serving for windows clients 
enable_clamav: false


