---
# Any global variables needed to be known ACROSS roles and hosts
# should be defined here.

required_domains:
        - openpgpkey
        - wkd
        - autoconfig
        - autodiscover
        - mta-sts
        - imap
        - pop3
        - smtp

extra_domains:
        - dav
        - webmail

subdomains: "{{ required_domains + extra_domains }}"

timezone: "US/Eastern"

max_attachment_sizeM: 32
max_attachment_size: "{{ max_attachment_sizeM * 1048576 }}"

relayd_interface: 127.0.0.1
relayd_port: 1729
https_interface: 127.0.0.1
https_port: 1984
http_interface: egress
http_port: 80

# this part deals with enabling
# webmail, caldav and carddav
enable_extras: false
extrasIP: 127.0.0.1
extras_interface: "{{ https_interface }}"
extras_port: "{{ relayd_port }}"
extras_not_home: false


# other optionals
enable_nsd: false

enable_spamd: false

enable_clamav: false

username_delimiter: "+"

