---
# Any global variables needed to be known ACROSS roles
# should be defined here.
# Currently, only enabling/disabling roles needs to be
# done here

# pre-ansimail

# base

# nsd
enable_nsd: false

# acme

# spamd
enable_spamd: false

# rspamd

# clamav
enable_clamav: false

# smtpd
username_delimiter: "+"

# dovecot
