---
- name: Install PostgreSQL packages
  openbsd_pkg:
    name: "{{ item }}"
    state: present
  with_items: "{{ PSQL_packages }}"
  when: false

- name: Set up permissions on /var/www/{tmp,run}
  file:
    path: /var/www/{{ item }}
    state: directory
    mode: 01775
    owner: www
    group: www
  with_items:
    - tmp
    - run
  notify: Restart PostgreSQL

- name: Add postgres user to www group
  user:
    name: _postgresql
    groups: www
    append: yes
  notify: Restart PostgreSQL

- name: Initialize PostgreSQL
  command: initdb -D /var/postgresql/data -U postgres -E UTF8 -A peer
  args:
    creates: /var/postgresql/data/PG_VERSION
  become: yes
  become_user: _postgresql
<<<<<<< Updated upstream

- name: ensure semmni for busy servers
  lineinfile:
    path: /etc/sysctl.conf
    regexp: "^kern.seminfo.semmni"
    line: "kern.seminfo.semmni=90"
  notify: sysctl semmni

- name: ensure semmns for busy servers
  lineinfile:
    path: /etc/sysctl.conf
    regexp: "^kern.seminfo.semmns"
    line: "kern.seminfo.semmns=2048"
  notify: sysctl semmns

- name: generate configuration
=======
  notify: Restart PostgreSQL
  when: false
  
- name: Generate PostgreSQL config
>>>>>>> Stashed changes
  template:
    src: postgresql.conf.j2
    dest: /var/postgresql/data/postgresql.conf
    owner: _postgresql
    group: _postgresql
    mode: 0600
<<<<<<< Updated upstream
  notify: restart postgresql
=======
  notify: Restart PostgreSQL
>>>>>>> Stashed changes

- name: Generate PostgreSQL user configs
  copy:
    src: '{{ item }}'
    dest: /var/postgresql/data/{{ item }}
    owner: _postgresql
    group: _postgresql
    mode: 0600
  with_items:
    - pg_hba.conf
    - pg_ident.conf
<<<<<<< Updated upstream
  notify: restart postgresql
=======
  notify: Restart PostgreSQL

- name: Ensure semmni for busy servers
  lineinfile:
    path: /etc/sysctl.conf
    regexp: "^kern.seminfo.semmni"
    line: "kern.seminfo.semmni={{ PSQL_semmni }}"
  notify: Restart PostgreSQL

- name: Ensure semmns for busy servers
  lineinfile:
    path: /etc/sysctl.conf
    regexp: "^kern.seminfo.semmns"
    line: "kern.seminfo.semmns={{ PSQL_semmns }}"
  notify: Restart PostgreSQL
>>>>>>> Stashed changes

- meta: flush_handlers
