- name: Get ansimail UID
  shell: id -u ansimail
  register: ansimailUID

- name: Create mail directory
  file:
          path: /var/ansimail
          state: directory
          owner: ansimail
          group: ansimail
          mode: '0770'

- name: Set sieve directory permissions
  file:
          path: /usr/local/lib/dovecot/sieve
          state: directory
          owner: ansimail
          group: ansimail
          mode: '0770'

- name: Create sieve-before directory
  file:
          path: /var/dovecot/sieve/before
          state: directory
          owner: ansimail
          group: ansimail
          mode: '0770'

- name: Create sieve-pipe directory
  file:
          path: /var/dovecot/sieve-pipe
          state: directory
          owner: ansimail
          group: ansimail
          mode: '0770'

- name: Copy dovecot local configs
  copy:
          src: etc_dovecot_confd/
          dest: /etc/dovecot/conf.d/
          force: yes
          owner: ansimail
          group: ansimail
          mode: '0644'

- name: Generate dovecot ssl local config
  template:
          src: 10-mail.conf.j2
          dest: /etc/dovecot/conf.d/10-mail.conf
          owner: root
          group: wheel
          mode: '0644'

- name: Generate dovecot ssl local config
  template:
          src: 10-ssl.conf.j2
          dest: /etc/dovecot/conf.d/10-ssl.conf
          owner: root
          group: wheel
          mode: '0644'

- name: Add sievec scripts
  copy:
          src: sieve/
          dest: /usr/local/lib/dovecot/sieve/
          force: yes
          owner: ansimail
          group: ansimail
          mode: '0660'

- name: Add sieve shell scripts
  copy:
          src: sieve-shell/
          dest: /usr/local/lib/dovecot/sieve/
          force: yes
          owner: ansimail
          group: ansimail
          mode: '0770'

- name: Add quota warning script
  template:
          src: quota-warning.sh.j2
          dest: /usr/local/lib/dovecot/sieve/quota-warning.sh
          owner: ansimail
          group: ansimail
          mode: '0770'

- name: Add wks-server script
  template:
          src: wks-server.sh.j2
          dest: /usr/local/lib/dovecot/sieve/wks-server.sh
          owner: ansimail
          group: ansimail
          mode: '0770'

- name: Add sievec-before scripts
  copy:
          src: sieve-before/
          dest: /var/dovecot/sieve/before/
          force: yes
          owner: ansimail
          group: ansimail
          mode: '0660'

- name: Add wks-server sievec-before script
  template:
          src: 00-wks.sieve.j2
          dest: /var/dovecot/sieve/before/00-wks.sieve
          owner: ansimail
          group: ansimail
          mode: '0660'

- name: Do virtual-regen to start dovecot and smtpd
  shell: ansimail virtual-regen

