- name: Copy dovecot local configs
  copy:
          src: "{{ item.name }}"
          dest: /etc/dovecot/conf.d/
          owner: root
          group: wheel
          mode: '0644'
  with_items:
          - { name: "10-mail.conf" }
          - { name: "15-mailboxes.conf" }
          - { name: "20-imap.conf" }
          - { name: "90-plugin.conf" }

- name: Generate dovecot ssl local config
  template:
          src: 10-ssl.conf.j2
          dest: /etc/dovecot/conf.d/10-ssl.conf
          owner: root
          group: wheel
          mode: '0644'

- name: Restart dovecot
  service:
          name: dovecot
          state: restarted

- name: Add sieve scripts for spam and ham
  copy:
          src: "{{ item.name }}"
          dest: /usr/local/lib/dovecot/sieve/
          owner: root
          group: wheel
          mode: '0644'
  with_items: 
          - { name: "report-ham.sieve" }
          - { name: "report-spam.sieve" }

- name: Add autolearn scripts for spam and ham
  copy:
          src: "{{ item.name }}"
          dest: /usr/local/lib/dovecot/sieve/
          owner: root
          group: wheel
          mode: '0755'
  with_items: 
          - { name: "sa-learn-ham.sh" }
          - { name: "sa-learn-spam.sh" }

- name: sievec report spam
  shell: sievec report-spam.sieve
  args:
          chdir: /usr/local/lib/dovecot/sieve/

- name: sievec report ham
  shell: sievec report-ham.sieve
  args:
          chdir: /usr/local/lib/dovecot/sieve/

