- name: install clamd init script
  copy:
          src: clamd
          dest: /etc/rc.d/clamd
          mode: 0755
          owner: root
          group: bin

- name: Copy antivirus configs into rspamd
  copy:
          src: "{{ item.name }}"
          dest: "/etc/rspamd/local.d/{{ item.name }}"
          owner: root
          group: wheel
          mode: '0644'
  with_items:
          - { name: "antivirus.conf" }
          - { name: "antivirus_group.conf" }

- name: install freshclam conf
  copy:
          src: freshclam.conf
          dest: /etc/freshclam.conf
  notify:
          - install freshclam list
          - restart freshclam

- name: install clamd conf
  copy:
          src: clamd.conf
          dest: /etc/clamd.conf
  notify: restart clamd

- name: Reload rspamd
  service:
          name: rspamd
          state: reloaded

