- name: Install/Upgrade Excision Mail pre-requisites

  hosts: mainserver

  vars_files:
    - group_vars/global.yml
    - group_vars/pf.yml
    - group_vars/syslog.yml
    - vars.yml

  roles:
    - { role: base,          tags: ['base']           }
    - { role: pf,            tags: ['pf']             }
      when: enable_pf
    - { role: syslog,        tags: ['syslog']         }
      when: enable_syslog
    - { role: nsd,           tags: ['nsd']            }
