- name: Install/Upgrade Excision on this machine

  hosts: mainserver

  vars_files:
    - vars.yml
    - group_vars/global.yml

  roles:
    - { role: pre-excision,  tags: ['pre-excision']   }
    - { role: base,          tags: ['base']           }
    - { role: nsd,           tags: ['nsd']            }

