name: Install/Upgrade AnsiMail on this machine

hosts: local

vars_file:
        - vars.yml

roles:
        - { role: base,      tags: ['base']      }
        - { role: spamd,     tags: ['spamd']     }
        - { role: rspamd,    tags: ['rspamd']    }
        - { role: clamav,    tags: ['clamav']    }
        - { role: dovecot,   tags: ['dovecot']   }
        - { role: smtpd,     tags: ['smtpd']     }
        - { role: ssh,       tags: ['ssh']       }
        - { role: pf,        tags: ['pf']        }
        - { role: nsd,       tags: ['nsd']       }
        - { role: ansimail,  tags: ['ansimail']  }

