- name: Create httpd domain directory
  file:
          name: /var/www/{{ domain }}
          state: directory
          owner: root
          group: wheel
          mode: '0755'

- name: Create domain index file with Hello, World!
  copy:
          src: index.html
          dest: /var/www/{{ domain }}/index.html
          force: yes
          owner: root
          group: wheel
          mode: '0755'

- name: Create mail directory in httpd domain
  file:
          name: /var/www/{{ domain }}/mail
          state: directory
          owner: root
          group: wheel
          mode: '0755'

- name: Create autodiscover directory in httpd domain
  file:
          name: /var/www/{{ domain }}/Autodiscover
          state: directory
          owner: root
          group: wheel
          mode: '0755'

# https://wiki.mozilla.org/Thunderbird:Autoconfiguration#Implementation
- name: Copy mozilla config file to mail
  template:
          src: config-v1.1.xml.j2
          dest: /var/www/{{ domain }}/mail/config-v1.1.xml
          owner: root
          group: wheel
          mode: '0755'

# https://github.com/gronke/email-autodiscover/blob/master/mail/autodiscover.xml
# https://docs.microsoft.com/en-us/previous-versions/office/office-2010/cc511507(v=office.14)?redirectedfrom=MSDN#Anchor_3
- name: Copy autodiscover config file to autodiscover
  template:
          src: Autodiscover.xml.j2
          dest: /var/www/{{ domain }}/Autodiscover/Autodiscover.xml
          owner: root
          group: wheel
          mode: '0755'

- name: Create mta-sts directory
  file:
          name: /var/www/mta-sts
          state: directory
          owner: root
          group: wheel
          mode: '0755'

- name: Copy mta-sts.txt file
  template:
          src: mta-sts.txt.j2
          dest: /var/www/mta-sts/mta-sts.txt
          owner: root
          group: wheel
          mode: '0755'

- name: Create OpenPGP directory for WKD
  file:
          name: /var/www/openpgpkey
          state: directory
          owner: ansimail
          group: ansimail
          mode: '0755'
  notify: initialize gpg-wks-server

- name: Create httpd config
  template:
          src: httpd.conf.j2
          dest: /etc/httpd.conf
          owner: root
          group: wheel
          mode: '0644'
  notify: restart httpd

- name: Create acme config
  template:
          src: acme-client.conf.j2
          dest: /etc/ansimail/ssl/acme-client.conf
          owner: root
          group: wheel
          mode: '0644'
  notify: create acme certs

- meta: flush_handlers
