- name: Create httpd domain directory
  file:
          path: /var/www/htdocs/{{ domain }}
          state: directory
          owner: root
          group: wheel
          mode: '0755'

- name: Create httpd domain directory
  file:
          path: /var/www/htdocs/{{ item.name }}
          state: directory
          owner: root
          group: wheel
          mode: '0755'
  with_items: "{{ additional_domains }}"
  when: additional_domains is defined

- name: Create mail directory for mozilla autoconfig
  file:
          path: /var/www/mail/{{ domain }}
          state: directory
          owner: root
          group: wheel
          mode: '0755'

- name: Create mail directory for mozilla autoconfig for adomains
  file:
          path: /var/www/mail/{{ item.name }}
          state: directory
          owner: root
          group: wheel
          mode: '0755'
  with_items: "{{ additional_domains }}"
  when: additional_domains is defined

# https://wiki.mozilla.org/Thunderbird:Autoconfiguration#Implementation
- name: Copy mozilla config file to mail
  template:
          src: config-v1.1.xml.j2
          dest: /var/www/mail/{{ item.name }}/config-v1.1.xml
          owner: root
          group: wheel
          mode: '0755'
  with_items: 
          - name: "{{ domain }}"

- name: Copy mozilla config file to mail for adomains
  template:
          src: config-v1.1.xml.j2
          dest: /var/www/mail/{{ item.name }}/config-v1.1.xml
          owner: root
          group: wheel
          mode: '0755'
  with_items: "{{ additional_domains }}"
  when: additional_domains is defined

- name: Create autodiscover directory for microsoft autodiscover
  file:
          path: /var/www/Autodiscover/{{ domain }}
          state: directory
          owner: root
          group: wheel
          mode: '0755'

- name: Create autodiscover directory for microsoft autodiscover for adomains
  file:
          path: /var/www/Autodiscover/{{ item.name }}
          state: directory
          owner: root
          group: wheel
          mode: '0755'
  with_items: "{{ additional_domains }}"
  when: additional_domains is defined

# https://github.com/gronke/email-autodiscover/blob/master/mail/autodiscover.xml
# https://docs.microsoft.com/en-us/previous-versions/office/office-2010/cc511507(v=office.14)?redirectedfrom=MSDN#Anchor_3
- name: Copy autodiscover config file to autodiscover
  template:
          src: Autodiscover.xml.j2
          dest: /var/www/Autodiscover/{{ domain }}/Autodiscover.xml
          owner: root
          group: wheel
          mode: '0755'
  with_items:
          - name: "{{ domain }}"

- name: Copy autodiscover config file to autodiscover
  template:
          src: Autodiscover.xml.j2
          dest: /var/www/Autodiscover/{{ item.name }}/Autodiscover.xml
          owner: root
          group: wheel
          mode: '0755'
  with_items: "{{ additional_domains }}"
  when: additional_domains is defined

- name: Create mta-sts directory
  file:
          path: /var/www/mta-sts
          state: directory
          owner: root
          group: wheel
          mode: '0755'

- name: Copy mta-sts.txt file
  template:
          src: mta-sts.txt.j2
          dest: /var/www/mta-sts/mta-sts.txt
          owner: root
          group: wheel
          mode: '0755'

- name: Make gpg-wks-server hierarchy
  command: excision ensure-gpg

- name: Create httpd config
  template:
          src: httpd.conf.j2
          dest: /etc/httpd.conf
          owner: root
          group: wheel
          mode: '0644'
  notify: restart httpd

- name: Create relayd config
  template:
          src: relayd.conf.j2
          dest: /etc/relayd.conf
          owner: root
          group: wheel
          mode: '0644'

- name: Create acme config
  template:
          src: acme-client.conf.j2
          dest: /etc/excision/ssl/acme-client.conf
          owner: root
          group: wheel
          mode: '0644'

- name: Create acme certs
  command: excision renew-certs
  ignore_errors: true

- name: Create symlinks for relayd
  file:
          src: "/etc/excision/ssl/{{ item.name }}"
          dest: "/etc/ssl/{{ item.name }}"
          owner: root
          group: wheel
          state: link
  with_items:
          - name: "private/{{ domain }}.key"
          - name: "{{ domain }}.crt"
          - name: "{{ domain }}.ocsp"

- name: Restart relayd
  service:
          name: relayd
          state: restarted

- meta: flush_handlers
