---
- name: Create acme config
  template:
          src: acme-client.conf.j2
          dest: /etc/excision/ssl/acme-client.conf
          owner: root
          group: wheel
          mode: '0644'

- name: Create acme certs
  command: excision renew-certs
  ignore_errors: true

- name: Create symlinks for relayd certificates
  file:
          src: "/etc/excision/ssl/{{ item.name }}"
          dest: "/etc/ssl/{{ item.name }}"
          owner: root
          group: wheel
          state: link
  with_items:
          - name: "private/{{ domains[0].name }}.key"
          - name: "{{ domains[0].name }}.crt"
          - name: "{{ domains[0].name }}.ocsp"

- name: Create relayd config
  template:
          src: relayd.conf.j2
          dest: /etc/relayd.conf
          owner: root
          group: wheel
          mode: '0600'

- name: Restart relayd
  service:
          name: relayd
          state: restarted
          enabled: yes

- meta: flush_handlers
