- name: Create httpd config
  template:
          src: httpd.conf.j2
          dest: /etc/httpd.conf
          owner: root
          group: wheel
          mode: '0644'
  notify: restart httpd

- name: Create acme config
  template:
          src: acme-client.conf.j2
          dest: /etc/ansimail/acme-client.conf
          owner: root
          group: wheel
          mode: '0644'

- name: Create acme certs
  command: acme-client -f /etc/ansimail/acme-client.conf {{ hostname }}
  ignore_errors: yes

- name: Create dkim certs
  command: ansimail ensure-dkim {{ domain }}
  notify: generate TXT records

- meta: flush_handlers
