---
- name: Install required packages
  openbsd_pkg:
    name: "{{ PE_packages }}"
    state: present

- name: Enable required services
  service:
    name: "{{ item.name }}"
    enabled: true
  with_items: "{{ PE_services }}"

- name: Create Excision config directories
  file:
    name: "{{ item.name }}"
    state: directory
    owner: root
    group: wheel
    mode: "{{ item.perm }}"
  with_items: "{{ PE_config_dirs }}"

- name: Create hostname file
  template:
    src: hostname.j2
    dest: /etc/excision/nsd/hostname
    mode: '0644'

- name: Make required groups
  group:
    name: "{{ item.name }}"
  with_items:
    - {name: "excision"}
    - {name: "excision-passwd"}

- name: Make excision user
  user:
    name: excision
    comment: Excision general manager
    group: excision
    groups: ""
    login_class: daemon
    shell: /bin/ksh
    home: /var/excision-home
    password_lock: true
    password: "*************"

- name: Disable logins for excision user
  file:
    state: absent
    path: /var/excision-home/.ssh/

- name: Generate admin_ssh_password hash for excision-passwd user
  shell: printf %s\\n "{{ admin_ssh_password }}" | encrypt
  register: _PE_password_hash

- name: Make excision-passwd user
  user:
    name: excision-passwd
    comment: Excision password manager
    group: excision-passwd
    groups: excision
    login_class: default
    shell: /bin/ksh
    home: /var/excision-passwd
    password: "{{ _PE_password_hash.stdout }}"

- name: Allow excision-passwd to execute proper command
  lineinfile:
    path: /etc/doas.conf
    create: true
    owner: root
    group: wheel
    mode: '0600'
    state: present
    regexp: 'permit nopass excision-passwd.*'
    line: >
      permit nopass excision-passwd
      as root
      cmd /usr/local/bin/excision-change-user-passwd

- name: Install gpg-wks init script
  copy:
    src: excision-wks-init
    dest: /var/excision-home/
    force: true
    owner: excision
    group: excision
    mode: '0755'

- name: Install `excision` command
  copy:
    src: "{{ item.name }}"
    dest: /usr/local/bin/
    force: true
    owner: root
    group: wheel
    mode: '0755'
  with_items:
    - name: excision
    - name: excision-change-user-passwd

- name: Install Excision scripts
  copy:
    src: excision_scripts/
    dest: /usr/local/lib/excision/
    force: true
    owner: root
    group: wheel
    mode: '0755'

- name: Install `excision` man page
  copy:
    src: files/man8/excision.8
    dest: /usr/local/man/man8/
    owner: root
    group: bin
    mode: '0644'
  notify: Update man database
