- name: rebuild login database
  command: cap_mkdb /etc/login.conf

- name: reload syslog
  service:
    name: syslogd
    state: reloaded

- name: reload newsyslog
  command: newsyslog

- name: reload pf
  command: pfctl -f /etc/pf.conf

