- name: Install required packages
  openbsd_pkg:
          name: {{ item }}
          state: present
  with_items: { dovecot, dovecot-pigeonhole, rspamd, opensmtpd-filter-rspamd, opensmtpd-filter-senderscore, redis, maildrop }

- name: Install ClamAV if needed
  openbsd_pkg:
          name: clamav
          state: present
  when: enable_clamav|default(false)|bool

- name: Make AnsiMail user
  user:
          name: _ansimail
          comment: AnsiMail manager
          system: yes
          group: _ansimail
          append: yes
          groups: wheel, _smtpd, _rspamd, _clamav, _sshd 
          login_class: default
          shell: /sbin/nologin
          create_home: no

- name: Make AnsiMail ssh group
  group:
          name: ansimail-ssh

- name: Create AnsiMail scripts directory
  file:
          name: /usr/local/share/ansimail
          state: directory
          owner: _ansimail
          group: wheel
          mode: '0755'

- name: Create AnsiMail base config directory
  file:
          name: /etc/ansimail
          state: directory
          owner: _ansimail
          group: wheel
          mode: '0755'

- name: Create DKIM public certificate directory
  file:
          name: /etc/ansimail/dkim
          state: directory
          owner: _ansimail
          group: wheel
          mode: '0755'

- name: Create DKIM private certificates directory
  file:
          name: /etc/ansimail/dkim/private
          state: directory
          owner: _ansimail
          group: wheel
          mode: '0750'

- name: Create Lets Encrypt public certificates directory
  file:
          name: /etc/ansimail/ssl
          state: directory
          owner: _ansimail
          group: wheel
          mode: '0755'

- name: Create Lets Encrypt private certificates directory
  file:
          name: /etc/ansimail/ssl/private
          state: directory
          owner: _ansimail
          group: wheel
          mode: '0750'

- name: Create NSD config directory
  file:
          name: /etc/ansimail/nsd
          state: directory
          owner: _ansimail
          group: wheel
          mode: '0755'

