- name: Install required packages
  openbsd_pkg:
          name: "{{ item.name }}"
          state: present
  with_items: 
          - { name: "dovecot" }
          - { name: "dovecot-pigeonhole" }
          - { name: "clamav" }
          - { name: "rspamd" }
          - { name: "opensmtpd-filter-rspamd" }
          - { name: "opensmtpd-filter-senderscore" }
          - { name: "redis" }

- name: Enable required services
  service:
          name: "{{ item.name }}"
          enabled: yes
  with_items:
          - { name: "redis" }
          - { name: "freshclam" }
          - { name: "clamd" }
          - { name: "rspamd" }
          - { name: "dovecot" }
          - { name: "nsd" }
          - { name: "httpd" }

- name: Make AnsiMail user
  user:
          name: ansimail
          comment: AnsiMail manager
          system: yes
          group: wheel
          append: yes
          groups: _smtpd, _rspamd, _clamav, sshd 
          login_class: daemon
          shell: /sbin/nologin
          home: /nonexistent
          create_home: no

- name: Make AnsiMail ssh group
  group:
          name: ansimail-ssh

- name: Create AnsiMail scripts directory
  file:
          name: /usr/local/lib/ansimail
          state: directory
          owner: root
          group: wheel
          mode: '0755'

- name: Install `ansimail` command
  copy:
          src: ansimail
          dest: /usr/local/bin/
          owner: root
          group: wheel
          mode: '0755'

- name: Install AnsiMail scripts
  copy:
          src: ansimail_scripts/
          dest: /usr/local/lib/ansimail/
          owner: root
          group: wheel
          mode: '0644'

- name: Create AnsiMail base config directory
  file:
          name: /etc/ansimail
          state: directory
          owner: root
          group: wheel
          mode: '0755'

- name: Create DKIM public certificate directory
  file:
          name: /etc/ansimail/dkim
          state: directory
          owner: root
          group: wheel
          mode: '0755'

- name: Create DKIM private certificates directory
  file:
          name: /etc/ansimail/dkim/private
          state: directory
          owner: root
          group: wheel
          mode: '0755'

- name: Create Lets Encrypt public certificates directory
  file:
          name: /etc/ansimail/ssl
          state: directory
          owner: root
          group: wheel
          mode: '0755'

- name: Create Lets Encrypt private certificates directory
  file:
          name: /etc/ansimail/ssl/private
          state: directory
          owner: root
          group: wheel
          mode: '0755'

- name: Create NSD config directory
  file:
          name: /etc/ansimail/nsd
          state: directory
          owner: root
          group: wheel
          mode: '0755'

