- name: Install required packages
  openbsd_pkg:
          name: "{{ item.name }}"
          state: latest
  with_items: 
          - { name: "dovecot" }
          - { name: "dovecot-pigeonhole" }
          - { name: "clamav" }
          - { name: "rspamd" }
          - { name: "opensmtpd-filter-rspamd" }
          - { name: "opensmtpd-filter-senderscore" }
          - { name: "opensmtpd-extras" }
          - { name: "redis" }

- name: Enable required services
  service:
          name: "{{ item.name }}"
          enabled: yes
  with_items:
          - { name: "redis" }
          - { name: "freshclam" }
          - { name: "clamd" }
          - { name: "rspamd" }
          - { name: "dovecot" }
          - { name: "nsd" }
          - { name: "httpd" }
          - { name: "spamd" }

- name: Create AnsiMail config directories
  file:
          name: "{{ item.name }}"
          state: directory
          owner: root
          group: wheel
          mode: "{{ item.perm }}"
  with_items:
          - { name: "/etc/ansimail/dkim/private", perm: "0755" }
          - { name: "/etc/ansimail/ssl/private", perm: "0755" }
          - { name: "/etc/ansimail/nsd", perm: "0755" }
          - { name: "/etc/ansimail/spam", perm: "0755" }
          - { name: "/etc/ansimail/users", perm: "0700" }
          - { name: "/etc/ansimail/users/user-data", perm: "0700" }

- name: Make required groups
  group:
          name: ansimail

- name: Make AnsiMail user
  user:
          name: ansimail
          comment: AnsiMail manager
          group: ansimail
          groups: ""
          login_class: daemon
          shell: /bin/ksh
          home: /var/ansimail-home

- name: Install gpg-wks init script
  copy:
          src: ansimail-wks-init
          dest: /var/ansimail-home/
          force: yes
          owner: ansimail
          group: ansimail
          mode: "0644"

- name: Create AnsiMail scripts directory
  file:
          name: /usr/local/lib/ansimail/helpers
          state: directory
          force: yes
          owner: root
          group: wheel
          mode: '0700'

- name: Install `ansimail` command
  copy:
          src: ansimail
          dest: /usr/local/bin/
          force: yes
          owner: root
          group: wheel
          mode: '0700'

- name: Install AnsiMail scripts
  copy:
          src: ansimail_scripts/
          dest: /usr/local/lib/ansimail/
          force: yes
          owner: root
          group: wheel
          mode: '0600'

