---
ssh_port: 22

BASE_logfiles:
  - {file: "/var/www/logs/access.log", size: "*", when: "$W0", command: "pkill -USR1 -u root -U root -x httpd"}
  - {file: "/var/www/logs/error.log", size:"250", command:"pkill -USR1 -u root -U root -x httpd"}
  - {file: "/var/log/doas"}
  - {file: "/var/log/ldapd"}
  - {file: "/var/log/nsd"}
  - {file: "/var/log/spamd"}
  - {file: "/var/log/dovecot"}
  - {file: "/var/log/clamd"}
  - {file: "/var/log/freshclam"}
  - {file: "/var/log/rspamd/rspamd.log", user:"_rspamd", group:"_rspamd", count:1, command: "pkill -USR1 -u _rspamd -U _rspamd -x rspamd"}
