- name: install freshclam list
  command: freshclam

- name: restart clamd
  service:
          name: clamd
          enabled: yes
          state: restarted

- name: restart freshclam
  service:
          name: freshclam
          enabled: yes
          state: restarted

