- name: Copy mailname
  template:
          src: mailname.j2
          dest: /etc/mail/mailname

- name: Copy vdomains
  template:
          src: vdomains.j2
          dest: /etc/mail/vdomains

- name: Generate zone master file
  template:
          src: domain.zone.j2
          dest: /etc/ansimail/nsd/{{ domain }}.zone
          owner: root
          group: wheel
          mode: '0644'

- name: Add SSHFP records to zone master file
  shell: ssh-keygen -r {{ hostname }} >> /etc/ansimail/nsd/{{ domain }}.zone

- name: Copy addon file
  shell: cat {{ nsd_addon }} > /etc/ansimail/nsd/{{ domain }}.zone.addon
  when: nsd_addon is defined

- name: Actually generate the required config if the needed
  include: nsd_optional.yml
  when: (enable_nsd is defined) and (enable_nsd == true)
