---
- name: Copy mailname
  template:
    src: mailname.j2
    dest: /etc/mail/mailname
    owner: root
    group: wheel
    mode: '0644'

- name: Copy vdomains
  template:
    src: vdomains.j2
    dest: /etc/mail/vdomains
    owner: root
    group: wheel
    mode: '0644'

- name: Generate zone master files
  template:
    src: domain.zone.j2
    dest: "/etc/excision/nsd/{{ item.name }}.zone"
    owner: root
    group: wheel
    mode: '0644'
  with_items: "{{ domains }}"

- name: Generate all dkim certificates
  command: excision ensure-dkim
  ignore_errors: true

- name: Add SSHFP records to zone master file
  shell: >
    ssh-keygen -r "{{ hostname.split('.')[:-2] | join('.') }}"
    >> "/etc/excision/nsd/{{ domains[0].name }}.zone"

- name: Actually generate the required config if the needed
  include: nsd_optional.yml
  when: enable_nsd

- name: Copy private keys for davical
  include: nsd_davical.yml
  when: enable_extras
