---
- name: Synchronize davical private keys
  command: >
    openrsync
    -e "ssh -i $HOME/.ssh/id_ed25519 -p22"
    --rsync-path="/usr/bin/openrsync"
    "/etc/excision/dkim/private/davRSA.{{ item.name }}.key"
    "root@{{ extrasIP }}:/var/www/etc/davical/keys/"
  with_items: "{{ domains }}"
  when: extras_not_home

- name: Copy davical private keys
  copy:
    src: /etc/excision/dkim/private/dav.{{ item.name }}.key
    dest: /var/www/etc/davical/keys/
    remote_src: true
  with_items: "{{ domains }}"
  when: not extras_not_home
