- name: Generate nsd conf
  template:
          src: nsd.conf.j2
          dest: /var/nsd/etc/nsd.conf
          owner: root
          group: _nsd
          mode: '0640'

- name: Generate the temporary nsd zone file
  command: ansimail ensure-zone

- name: Move the temporary file to proper one
  copy: 
          src: /var/nsd/zones/master/{{ domain }}.zone.tmp 
          dest: /var/nsd/zones/master/{{ domain }}.zone
          remote_src: yes
          mode: preserve

- name: Restart nsd
  service:
          name: nsd
          state: restarted


