---
# this is the ugliest hack in this whole instalation
# i am full of regret with being unable to get a nicer
# method for figuring out how to send private keys
# to the extraserver, (unless combining site-install and site-extrasIP
# and then setting facts - NOT GOING TO DO THIS)
- name: Synchronize davical private keys
  command: >
    openrsync
    -e "ssh -i $HOME/.ssh/id_ed25519 -p22"
    --rsync-path="mkdir -p /var/www/etc/davical/keys && /usr/bin/openrsync"
    "/etc/excision/dkim/private/davRSA.{{ item.name }}.key"
    "root@{{ extrasIP }}:/var/www/etc/davical/keys/"
  with_items: "{{ domains }}"
  when: extras_not_home

- name: Copy davical private keys
  copy:
    src: /etc/excision/dkim/private/dav.{{ item.name }}.key
    dest: /var/www/etc/davical/keys/
    force: true
    remote_src: true
  with_items: "{{ domains }}"
  when: not extras_not_home
