- name: enable redis
  service:
          name: redis
          enabled: yes
          state: restarted

- name: generate certificates
  script: generate_certificates.sh {{ domain }}

- name: enable rspamd
  service:
          name: rspamd
          enabled: yes
          state: restarted

