- name: Generate aliases table
  template:
          src: aliases.j2
          dest: /etc/mail/{{ item }}
  with_items: aliases

- name: Generate smtpd config
  template:
          src: smtpd.conf.j2
          dest: /etc/mail/smtpd.conf
  notify: restart smtpd

- meta: flush_handlers
