- name: Copy base aliases file
  template:
          src: aliases.j2
          dest: /etc/ansimail/users/aliases.base
          owner: root
          group: wheel
          mode: '0600'

- name: Copy base virtual file
  template:
          src: virtual.j2
          dest: /etc/ansimail/users/virtual.base
          owner: root
          group: wheel
          mode: '0600'

- name: Copy mailname
  template:
          src: mailname.j2
          dest: /etc/ansimail/users/mailname
          owner: root
          group: wheel
          mode: '0600'

- name: Copy vdomains
  template:
          src: vdomains.j2
          dest: /etc/ansimail/users/vdomains
          owner: root
          group: wheel
          mode: '0600'

- name: Make sure that passwd file exists
  file:
          path: /etc/ansimail/users/passwd
          state: touch
          owner: root
          group: wheel
          mode: '0600'

- name: Create user-data folder
  file:
          path: /etc/ansimail/users/user-data
          state: directory
          owner: root
          group: wheel
          mode: '0700'

- name: Add admin user with random password (ignore if already exists)
  shell: openssl rand -hex 32 | ansimail add-user {{ admin }}
  ignore_errors: yes

- name: Add wks user with random password (ignore if already exists)
  shell: openssl rand -hex 32 | ansimail add-user "wks"
  ignore_errors: yes

- name: Generate smtpd data files (virtuals, aliases, passwd, mailname, vdomains)
  shell: ansimail smtp-gendata

# Any items belonging to _smtpd group are 640 and wheel are 644
# passwd is an exception as it needs to be read by both dovecot and smtpd
- name: Make sure that needed files exist with proper permissions
  file:
          path: "/etc/mail/{{ item.name }}"
          state: touch
          owner: "{{ item.user }}"
          group: "{{ item.group }}"
          mode: "{{ item.perm }}"
  with_items:
          - { name: "aliases", user: "root", group: "_smtpd",  perm: "0640" }
          - { name: "mailname", user: "root", group: "wheel", perm: "0644" }
          - { name: "virtual", user: "root", group: "_smtpd", perm: "0640" }
          - { name: "vdomains", user: "root", group: "wheel", perm: "0644" }
          - { name: "passwd", user: "_smtpd", group: "_dovecot", perm: "0440" }

- name: Generate smtpd config
  template:
          src: smtpd.conf.j2
          dest: /etc/mail/smtpd.conf
          owner: root
          group: wheel
          mode: '0644'

- name: Restart smtpd
  service:
          name: smtpd
          state: restarted
