- name: Generate aliases table
  template:
          src: aliases.j2
          dest: /etc/mail/aliases
          owner: root
          group: wheel
          mode: '0644'

- name: Generate smtpd config
  template:
          src: smtpd.conf.j2
          dest: /etc/mail/smtpd.conf
          owner: root
          group: wheel
          mode: '0644'

- name: Restart smtpd
  service:
          name: smtpd
          state: restarted
