---
- name: generate local aliases file
  template:
    src: aliases.j2
    dest: /etc/mail/aliases

- name: add admin user for primary domain with random password (ignore if it already exists)
  shell: openssl rand -hex 32 | excision add-user "{{ admin }}@{{ domains[0].name }}"
  ignore_errors: yes

- name: add wks user for all domains with random password (ignore if they already exists)
  shell: openssl rand -hex 32 | excision add-user "wks@{{ item.name }}"
  ignore_errors: yes
  with_items: "{{ domains }}"

- name: add all the needed aliases for admin for all domains (ignore if they already exist)
  command: excision add-alias "{{ item[0] }}@{{ item[1].name }}" "{{ admin }}@{{ domains[0].name }}"
  ignore_errors: yes
  with_nested:
    - "{{ smtpd_aliases }}"
    - "{{ domains }}"

- name: ensure all smtpd table files exist
  file:
    path: "/etc/mail/{{ item.name }}"
    state: touch
    mode: "{{ item.perm }}"
    owner: "{{ item.user }}"
    group: "{{ item.group }}"
    modification_time: preserve
    access_time: preserve
  with_items: "{{ smtpd_tables }}"

- name: generate smtpd config
  template:
    src: smtpd.conf.j2
    dest: /etc/mail/smtpd.conf
    mode: '0644'
    owner: root
    group: wheel
