- name: restart httpd
  service:
          name: httpd
          state: restarted

- name: create acme certs
  command: acme-client -f /etc/ansimail/ssl/acme-client.conf "{{ hostname }}.{{ domain }}"
  ignore_errors: true
