---

pre_excision_packages:
  - "dovecot"
  - "dovecot-pigeonhole"
  - "gnupg--%gnupg2"
  - "opensmtpd-extras"
  - "opensmtpd-filter-rspamd"
  - "opensmtpd-filter-senderscore"
  - "redis"
  - "rspamd"
