- name: Create rspamd local.d directory
  file:
          path: /etc/rspamd/local.d/
          state: directory
          owner: root
          group: wheel
          mode: '0755'

- name: Create rspamd local confs
  copy:
          src: etc_rspamd_locald/
          dest: /etc/rspamd/local.d/
          force: yes
          owner: root
          group: wheel
          mode: '0644'

- name: Create dkim_signing config
  template:
          src: dkim_signing.conf.j2
          dest: /etc/rspamd/local.d/dkim_signing.conf
          owner: root
          group: wheel
          mode: '0644'

- name: Create phishing config
  template:
          src: phishing.conf.j2
          dest: /etc/rspamd/local.d/phishing.conf
          owner: root
          group: wheel
          mode: '0644'

- name: Create surbl config
  template:
          src: surbl.conf.j2
          dest: /etc/rspamd/local.d/surbl.conf
          owner: root
          group: wheel
          mode: '0644'

- name: Check redis is started
  service:
          name: redis
          state: started

- name: Check rspamd is started
  service:
          name: rspamd
          state: started

- name: Check rspamd is reloaded
  service:
          name: rspamd
          state: reloaded

- name: Download pretrained datasets
  include: bayes_pretrain.yml
  when: rspamd_enable_pretrain
