---
- name: Add _rspamd to _redis group
  user:
    name: _rspamd
    groups: _redis
    append: yes
    create_home: no

- name: Create rspamd local.d directory
  file:
    path: /etc/rspamd/local.d/
    state: directory
    owner: root
    group: wheel
    mode: '0755'

- name: Create rspamd local confs
  copy:
    src: etc_rspamd_locald/
    dest: /etc/rspamd/local.d/
    force: true
    owner: root
    group: wheel
    mode: '0644'

- name: Create rspamd local templated confs
  template:
    src: "{{ item.name }}"
    dest: "/etc/rspamd/local.d/{{ item.name | replace('.j2', '') }}"
    owner: root
    group: wheel
    mode: '0644'
  with_items: "{{ rspamd_templates }}"

- name: Check rspamd is started
  service:
    name: rspamd
    state: started

- name: Check rspamd is reloaded
  service:
    name: rspamd
    state: reloaded
