- name: Create dkim certs for domain
  include: openssl.yml

- name: Create rspamd local.d directory
  file:
          name: /etc/rspamd/local.
          state: directory
          owner: root
          group: wheel
          mode: '0755'

- name: Create rspamd local confs
  copy:
          src: etc_rspamd_locald/
          dest: /etc/rspamd/local.d/
          owner: root
          group: wheel
          mode: '0644'

- name: Create dkim_signing config
  template:
          src: local.d/dkim_signing.conf.j2
          dest: /etc/rspamd/local.d/dkim_signing.conf

