- name: generate private keys
  command: openssl genrsa -out '{{ dkim_home }}/private/ansimail.{{ domain }}.key' 2048
  args:
          creates: '{{ dkim_home }}/private/ansimail.{{ domain }}.key'

- name: generate public keys
  command: openssl rsa -in '{{ dkim_home }}/private/ansimail.{{ domain }}.key' -pubout -out '{{ dkim_home }}/ansimail.{{ domain }}.pub'
  args:
          creates: '{{ dkim_home }}/ansimail.{{ domain }}.pub'

- name: generate TXT records
  shell: ( awk 'NR>2 {print last} {last=$0}' ORS='' {{ dkim_home }}/ansimail.{{ domain }}.pub ) | fold -w255 | awk 'BEGIN { print "ansimail._domainkey\tIN\tTXT\t(\"v=DKIM1;k=rsa;p=\"" } { print " " "\"" $0 "\"" } END { print " \";\")" }' | tr -d '\n' > {{ dkim_home }}/ansimail.{{ domain }}.txt
  args:
          creates: '{{ dkim_home }}/ansimail.{{ domain }}.txt' 

