---
- name: Install required packages
  openbsd_pkg:
    name: "{{ pre_excision_packages }}"
    state: present

- name: Enable required services
  service:
    name: "{{ item.name }}"
    enabled: true
  with_items:
    - {name: "dovecot"}
    - {name: "httpd"}
    - {name: "redis"}
    - {name: "relayd"}
    - {name: "rspamd"}

- name: Create Excision config directories
  file:
    name: "{{ item.name }}"
    state: directory
    owner: root
    group: wheel
    mode: "{{ item.perm }}"
  with_items:
    - {name: "/etc/excision/dkim/private", perm: "0755"}
    - {name: "/etc/excision/ssl/private", perm: "0755"}
    - {name: "/etc/excision/nsd", perm: "0755"}
    - {name: "/etc/excision/spam", perm: "0755"}
    - {name: "/etc/excision/users", perm: "0700"}
    - {name: "/etc/excision/users/user-data", perm: "0700"}

- name: Create hostname file
  template:
    src: hostname.j2
    dest: /etc/excision/nsd/hostname

- name: Make required groups
  group:
    name: excision

- name: Make Excision user
  user:
    name: excision
    comment: Excision general manager
    group: excision
    groups: ""
    login_class: daemon
    shell: /bin/ksh
    home: /var/excision-home

- name: Make Excision password managing user
  user:
    name: excision-passwd
    comment: Excision password manager
    group: excision
    groups: ""
    login_class: default
    shell: /bin/ksh
    home: /var/excision-passwd

- name: Allow excision-passwd to execute proper command
  lineinfile:
    path: /etc/doas.conf
    create: true
    owner: root
    group: wheel
    mode: '0600'
    state: present
    line: >
      permit nopass
      excision-passwd as root
      cmd /usr/local/bin/excision-change-user-passwd

- name: Install gpg-wks init script
  copy:
    src: excision-wks-init
    dest: /var/excision-home/
    force: true
    owner: excision
    group: excision
    mode: '0644'

- name: Create Excision scripts directory
  file:
    path: /usr/local/lib/excision/helpers
    state: directory
    force: true
    owner: root
    group: wheel
    mode: '0700'

- name: Install `excision` command
  copy:
    src: "{{ item.name }}"
    dest: /usr/local/bin/
    force: true
    owner: root
    group: wheel
    mode: '0700'
  with_items:
    - name: excision
    - name: excision-change-user-passwd

- name: Install Excision scripts
  copy:
    src: excision_scripts/
    dest: /usr/local/lib/excision/
    force: true
    owner: root
    group: wheel
    mode: '0700'

- name: Install `excision` man page
  copy:
    src: files/man8/excision.8
    dest: /usr/local/man/man8/
    owner: root
    group: bin
    mode: '0644'
  register: man_updated

- name: Update man database
  when: man_updated
  command: makewhatis
