- name: Generate login.conf
  copy:
          src: login.conf
          dest: /etc/login.conf
          owner: root
          group: wheel
          mode: '0644'
  notify: rebuild login database

- name: Make sure log files exist
  copy:
          content: ""
          dest: /var/log/{{ item }}
          force: no
          owner: root
          group: wheel
          mode: '0640'
  with_items: { nsd, httpd, doas, clamd, freshclam}

- name: Generate syslog conf
  copy:
          src: syslog.conf
          dest: /etc/syslog.conf
          owner: root
          group: wheel
          mode: '0644'
  notify: reload syslog

- name: Generate newsyslog conf
  copy:
          src: newsyslog.conf
          dest: /etc/newsyslog.conf
          owner: root
          group: wheel
          mode: '0644'
  notify: reload newsyslog

- name: Generate pf config
  template:
          src: pf.conf.j2
          dest: /etc/pf.conf
          owner: root
          group: wheel
          mode: '0600'
  notify: reload pf

- meta: flush_handlers
