---
- name: include packages
  include: packages.yml

- name: include services
  include: services.yml

- name: include users
  include: users.yml

- name: include scripts
  include: scripts.yml

- name: include configs
  include: configs.yml

- meta: flush_handlers
