- name: Generate login.conf
  copy:
          src: login.conf
          dest: /etc/login.conf
          force: yes
          owner: root
          group: wheel
          mode: '0644'
  notify: rebuild login database

- name: Make sure log files exist
  file:
          path: /var/log/{{ item }}
          state: touch
          owner: root
          group: wheel
          mode: '0640'
  with_items: { nsd, httpd, doas, clamd, freshclam, spamd}

- name: Generate syslog conf
  copy:
          src: syslog.conf
          dest: /etc/syslog.conf
          force: yes
          owner: root
          group: wheel
          mode: '0644'
  notify: reload syslog

- name: Generate newsyslog conf
  copy:
          src: newsyslog.conf
          dest: /etc/newsyslog.conf
          force: yes
          owner: root
          group: wheel
          mode: '0644'
  notify: reload newsyslog

- name: Make sure nospamd exists
  file:
          path: /etc/ansimail/spam/nospamd
          state: touch
          owner: root
          group: wheel
          mode: '0644'

- name: Make sure bigmailers exists
  file:
          path: /etc/ansimail/spam/bigmailers
          state: touch
          owner: root
          group: wheel
          mode: '0644'

- name: Generate pf config
  template:
          src: pf.conf.j2
          dest: /etc/pf.conf
          owner: root
          group: wheel
          mode: '0600'
  notify: reload pf

- name: Install new root crontab file
  copy:
          src: cron
          dest: /var/cron/tabs/root
          force: yes
          owner: ansimail
          group: crontab
          mode: '0600'

- meta: flush_handlers
