---
- name: make required groups
  group:
    name: "{{ item.name }}"
  with_items:
    - {name: "excision"}
    - {name: "excision-passwd"}

- name: make excision user
  user:
    name: excision
    comment: Excision general manager
    group: excision
    groups: ""
    login_class: daemon
    shell: /bin/ksh
    home: /var/excision-home
    password_lock: true
    password: "*************"

- name: disable logins for excision user
  file:
    state: absent
    path: /var/excision-home/.ssh/

- name: generate ssh password hash for excision-passwd user
  shell: printf %s\\n "{{ base_excision_passwd_password }}" | encrypt
  register: _base_excision_passwd_password_hash

- name: make excision-passwd user
  user:
    name: excision-passwd
    comment: Excision password manager
    group: excision-passwd
    groups: excision
    login_class: default
    shell: /bin/ksh
    home: /var/excision-passwd
    password: "{{ _base_excision_passwd_password_hash.stdout }}"

- name: allow excision-passwd to execute proper command
  lineinfile:
    path: /etc/doas.conf
    create: true
    owner: root
    group: wheel
    mode: '0600'
    state: present
    regexp: 'permit nopass excision-passwd.*'
    line: >
      permit nopass excision-passwd
      as root
      cmd /var/excision-passwd/excision-change-user-passwd
