---
- name: install php extensions
  openbsd_pkg:
    name: "{{ item }}-{{ php_pkg_version }}"
    state: present
  with_items: "{{ php_extensions }}"

- name: install extension inis
  copy:
    src: "/etc/php-{{ php_version }}.sample/"
    dest: "/etc/php-{{ php_version }}/"
    remote_src: true

- name: create php directories
  file:
    path: /etc/php-fpm.d
    state: directory

- name: generate php config
  template:
    src: php.ini.j2
    dest: /etc/php-{{ php_version }}.ini

- name: generate php_fpm config
  copy:
    src: php-fpm.conf
    dest: /etc/php-fpm.conf
    force: false

- name: create etc inside chroot
  file:
    name: /var/www/etc
    state: directory

- name: copy ca certs into www chroot
  copy:
    src: /etc/ssl/cert.pem
    dest: /var/www/etc/ssl/cert.pem
    remote_src: true
    mode: preserve

- name: copy resolv.conf into www chroot
  copy:
    src: "{{ item }}"
    dest: "/var/www/{{ item }}"
    remote_src: true
    mode: preserve
  with_items:
    - /etc/resolv.conf
    - /etc/resolv.conf.tail

- name: enable and restart php-fpm
  service:
    name: "{{ php_fpm }}"
    enabled: true
    state: restarted
