- name: install php packages
  openbsd_pkg:
    name: "{{ item.name }}-{{ php_pkg_version }}"
    state: present
  with_items:
    - { name: "php" }
    - { name: "php-gd" }
    - { name: "php-pgsql" }
    - { name: "php-curl" }
    - { name: "php-pdo_pgsql" }
    - { name: "php-imap" }
    - { name: "php-ldap" }

- name: install extension inis
  copy:
    src: phpsample/
    dest: "/etc/php-{{ php_version }}/"

- name: create php directories
  file:
    path: /etc/php-fpm.d
    state: directory

- name: generate php config
  template:
    src: php.ini.j2
    dest: /etc/php-{{ php_version }}.ini

- name: enable and restart php-fpm
  service:
    name: "{{ php_fpm }}"
    enabled: yes
    state: restarted

