---
- name: reload postgresql
  service:
    name: postgresql
    state: reloaded

- name: restart postgresql
  service:
    name: postgresql
    state: restarted
    enabled: true

- name: sysctl semmni
  command: sysctl kern.seminfo.semmni=90

- name: sysctl semmns
  command: kern.seminfo.semmns=2048

