- name: enable daemon
  lineinfile:
          dest: /etc/rc.conf.local
          regexp: ^spamd_flags=
          line: spamd_flags="-G {{ spamd_passtime }}:{{ spamd_greyexp }}:{{ spamd_whiteexp }} -h {{ hostname }}.{{ domain }} -C /etc/ansimail/ssl/{{ domain }}.fullchain.pem -K /etc/ansimail/ssl/private/{{ domain }}.key"
          create: yes

- name: Restart spamd
  service:
          name: spamd
          state: restarted
