- name: enable daemon
  lineinfile:
          dest: /etc/rc.conf.local
          regexp: ^spamd_flags=
          line: spamd_flags="-G {{ spamd_passtime }}:{{ spamd_greyexp }}:{{ spamd_whiteexp }} -h {{ hostname }} -C /etc/excision/ssl/{{ domains[0].name }}.crt -K /etc/excision/ssl/private/{{ domains[0].name }}.key"
          create: yes

- name: Restart spamd
  service:
          name: spamd
          state: restarted

- name: Add big mail corps
  command: excision whitelist-bigmailer "{{ item.name }}"
  with_items: "{{ bigmailers }}"
  ignore_errors: yes
