rfc_aliases:
        - "postmaster"
        - "abuse"
        - "noc"
        - "security"
        - "hostmaster"
        - "usenet"
        - "news"
        - "webmaster"
        - "dmarcreports"
        - "tlsreports"
        - "excision"
        - "calendar"
