name: "Push Notification"
on: [push, pull_request, create, issues, issue_comment]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: irc push
        uses: rectalogic/notify-irc@v1
        if: github.event_name == 'push'
        with:
          channel: "#excision-mail"
          nickname: excision-bot
          message: |
            ${{ github.actor }} has pushed to ${{ github.event.ref }}
            ${{ github.event.compare }}
            ${{ join(github.event.commits.*.message) }}
      - name: irc pull request
        uses: rectalogic/notify-irc@v1
        if: github.event_name == 'pull_request'
        with:
          channel: "#excision-mail"
          nickname: excision-bot
          message: |
            ${{ github.actor }} has opened PR 
            ${{ github.event.html_url }}
      - name: irc tag created
        uses: rectalogic/notify-irc@v1
        if: github.event_name == 'create' && github.event.ref_type == 'tag'
        with:
          channel: "#excision-mail"
          nickname: excision-bot
          message: |
            ${{ github.actor }} has tagged ${{ github.repository }}
            ${{ github.event.ref }}
      - name: irc issue
        uses: rectalogic/notify-irc@v1
        if: github.event_name == 'issues'
        with:
          channel: "#excision-mail"
          nickname: excision-bot
          message: |
            ${{ github.actor }} has ${{ github.event.action }} an issue
            ${{ github.event.issue.html_url }}
      - name: irc issue
        uses: rectalogic/notify-irc@v1
        if: github.event_name == 'issue_comment'
        with:
          channel: "#excision-mail"
          nickname: excision-bot
          message: |
            ${{ github.actor }} has ${{ github.event.action }} a comment on an issue
            ${{ github.event.issue.html_url }}
