name: ShellCheck Lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Shellcheck
      uses: ludeeus/action-shellcheck@0.1.0
    - name: ansible-lint
      uses: ansible/ansible-lint-action@v4.1.0.post0
