name: shellcheck

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Excision scripts
      run: |
        sudo mkdir -p /usr/local/bin /usr/local/lib/excision
        sudo cp roles/pre_excision/files/excision /usr/local/bin/
        sudo cp -r roles/pre_excision/files/excision_scripts/. /usr/local/lib/excision/
    - name: Run shellcheck
      uses: ludeeus/action-shellcheck@master
      with:
        scandir: './roles/pre_excision/files'
      env:
        SHELLCHECK_OPTS: -ax -e 1117,2034,2181
